//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ValuteData
{

    private ValuteDataValuteCursOnDate[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ValuteCursOnDate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ValuteDataValuteCursOnDate[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ValuteDataValuteCursOnDate
{

    private System.DateTime cursDateField;

    private bool cursDateFieldSpecified;

    private string vcodeField;

    private decimal vnomField;

    private bool vnomFieldSpecified;

    private decimal vcursField;

    private bool vcursFieldSpecified;

    private string vnameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime CursDate
    {
        get
        {
            return this.cursDateField;
        }
        set
        {
            this.cursDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CursDateSpecified
    {
        get
        {
            return this.cursDateFieldSpecified;
        }
        set
        {
            this.cursDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Vcode
    {
        get
        {
            return this.vcodeField;
        }
        set
        {
            this.vcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Vnom
    {
        get
        {
            return this.vnomField;
        }
        set
        {
            this.vnomField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VnomSpecified
    {
        get
        {
            return this.vnomFieldSpecified;
        }
        set
        {
            this.vnomFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal Vcurs
    {
        get
        {
            return this.vcursField;
        }
        set
        {
            this.vcursField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VcursSpecified
    {
        get
        {
            return this.vcursFieldSpecified;
        }
        set
        {
            this.vcursFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Vname
    {
        get
        {
            return this.vnameField;
        }
        set
        {
            this.vnameField = value;
        }
    }
}
