create PROCEDURE [dbo].[Service_ED_Import]
AS
BEGIN
	MERGE [dbo].[BIC_Dictionary] as [t]
	USING 
    (
		SELECT
			 [BIC]
            ,[BICDec]
            ,[NameP]
            ,[EnglName]
            ,[RegN]
            ,[CntrCd]
            ,[Rgn]
            ,[Ind]
            ,[Tnp]
            ,[Nnp]
            ,[Adr]
            ,[DateIn]
            ,[DateOut]
            ,[PtType]
            ,[Srvcs]
            ,[XchType]
            ,[UID]
            ,[ParticipantStatus]
            ,[Account]
            ,[RegulationAccType]
            ,[AccountCBRBIC]
            ,[AccountCBRBICDec]
            ,[AccountStatus]
            ,[UURSDate]
            ,[LWRSDate]
            ,[BusinessDay]
            ,[UpdateDay]
            ,[IsLicenseValid]
        FROM [dbo].[BIC_Dictionary_TMP]
    ) as [s]
    ON [t].[BIC] = [s].[BIC] AND [t].[Account] = [s].[Account]
    WHEN MATCHED THEN
        UPDATE SET
             [t].[BIC] = [s].[BIC]
            ,[t].[BICDec] = [s].[BICDec]
            ,[t].[NameP] = [s].[NameP]
            ,[t].[EnglName] = [s].[EnglName]
            ,[t].[RegN] = [s].[RegN]
            ,[t].[CntrCd] = [s].[CntrCd]
            ,[t].[Rgn] = [s].[Rgn]
            ,[t].[Ind] = [s].[Ind]
            ,[t].[Tnp] = [s].[Tnp]
            ,[t].[Nnp] = [s].[Nnp]
            ,[t].[Adr] = [s].[Adr]
            ,[t].[DateIn] = [s].[DateIn]
            ,[t].[DateOut] = [s].[DateOut]
            ,[t].[PtType] = [s].[PtType]
            ,[t].[Srvcs] = [s].[Srvcs]
            ,[t].[XchType] = [s].[XchType]
            ,[t].[UID] = [s].[UID]
            ,[t].[ParticipantStatus] = [s].[ParticipantStatus]
            ,[t].[Account] = [s].[Account]
            ,[t].[RegulationAccType] = [s].[RegulationAccType]
            ,[t].[AccountCBRBIC] = [s].[AccountCBRBIC]
            ,[t].[AccountCBRBICDec] = [s].[AccountCBRBICDec]
            ,[t].AccountStatus = [s].AccountStatus
            ,[t].[UURSDate] = [s].[UURSDate]
            ,[t].[LWRSDate] = [s].[LWRSDate]
            ,[t].[BusinessDay] = [s].[BusinessDay]
            ,[t].[UpdateDay] = [s].[UpdateDay]
            ,[t].[IsLicenseValid] = [s].[IsLicenseValid]
    WHEN NOT MATCHED THEN
        INSERT VALUES
        (
             [s].[BIC]
            ,[s].[BICDec]
            ,[s].[NameP]
            ,[s].[EnglName]
            ,[s].[RegN]
            ,[s].[CntrCd]
            ,[s].[Rgn]
            ,[s].[Ind]
            ,[s].[Tnp]
            ,[s].[Nnp]
            ,[s].[Adr]
            ,[s].[DateIn]
            ,[s].[DateOut]
            ,[s].[PtType]
            ,[s].[Srvcs]
            ,[s].[XchType]
            ,[s].[UID]
            ,[s].[ParticipantStatus]
            ,[s].[Account]
            ,[s].[RegulationAccType]
            ,[s].[AccountCBRBIC]
            ,[s].[AccountCBRBICDec]
            ,[s].AccountStatus
            ,[s].[UURSDate]
            ,[s].[LWRSDate]
            ,[s].[BusinessDay]
            ,[s].[UpdateDay]
            ,[s].[IsLicenseValid]
        );
END