CREATE TABLE [dbo].[Customer] (
    [CustomerID]            INT          IDENTITY (1, 1) NOT NULL,
    [AccountCode]             INT         not NULL,
    [CustomerAddress1]      VARCHAR (30) NULL,
    [CustomerAddress2]      VARCHAR (30) NULL,
    [CustomerAddress3]      VARCHAR (30) NULL,
    [BirthDate]             DATE NULL,
    [CustomerFirstName]     VARCHAR (30) NOT NULL,
    [CustomerMiddleName] VARCHAR (30)     NULL,
    [CustomerLastName]      VARCHAR (30) NOT NULL,
    [City]                  VARCHAR (20) NOT NULL,
    [State]                 VARCHAR (20)     NOT NULL,
    [ZipCode]               VARCHAR (10)    NOT NULL,
    [EmailAddress]          VARCHAR (40)    NOT NULL,
    [CellPhone]             VARCHAR (12) NOT NULL,
    [Residency]             varchar(5) not null,
    [KPP]                   varchar(35)  null,
    [OKATO]                 varchar(35)  null,
    CountryCode          varchar(5)   null,
    [Office_Name1]          varchar(30)  null,
    [Office_Name2]          varchar(30)  null,
    [Office_Name3]          varchar(30)  null,
    [IsClosed]              bit not null,
    [CloseDate]             date null,
    CONSTRAINT [pk_C_CustomerID] PRIMARY KEY CLUSTERED ([CustomerID] ASC),
);

