CREATE TABLE [dbo].[TempTasks] (
    [TaskID]          INT            NOT NULL,
    [IsEnabled]       BIT            NOT NULL,
    [TaskType]        INT            NULL,
    [Branch]          INT            NULL,
    [TaskName]        NVARCHAR (50)  NOT NULL,
    [LastWorkTime]    DATETIME       NULL,
    [TaskStartTime]   DATETIME       NOT NULL,
    [TaskEndTime]     DATETIME       NOT NULL,
    [Dependency]      NVARCHAR (100) NOT NULL,
    [FileMask]        NVARCHAR (30)     null,
    [FilePath]        NVARCHAR (50)  NULL,
    [Url]             NVARCHAR (50)  NULL,
    [FieldsCount]     INT            NULL,
    [FieldsSeparator] NVARCHAR (5)   NULL,
    [Params]          NVARCHAR(300)  NULL,
    SpName            NVARCHAR(100)  NULL,
    [ModifiedBy]      NVARCHAR (50)  NULL,
    [AuthoriziedBy]   NVARCHAR (50)  NULL,
    [Description]     NVARCHAR (250) NULL,
    [ManualStart]     BIT            NOT NULL
);
